title:       'Malav Patel'
description: ''
author:      'Malav Patel'

highlighter: rouge
permalink:   /:title
markdown:    kramdown
kramdown:
  math_engine: null

plugins:
  - jekyll-sitemap
  - jekyll-feed

collections:
  notes:
    output: true
  coding:
    output: true
